name: 'cocreate-s3'
description: 'uploads to cdn'
inputs:
  AWS_KEY_ID:  # id of input
    description: 'AWSKEYID'
    required: true
  AWS_ACCESS_KEY:  # id of input
    description: 'AWSACCESSKEY'
    required: true
  DIST_FILE_NAME:  # id of input
    description: 'file to be uploaded to s3'
    required: true
outputs:
  success: 
    description: 'successful'
runs:
  using: 'node12'
  main: './src/CoCreate-s3.js'
   

 