name: 'cocreate-s3'
description: 'uploads to cdn'
inputs:
  aws-key-id:  # id of input
    description: 'AWS_ACCESS_KEY'
    required: true
  aws-access-key:  # id of input
    description: 'AWS_ACCESS_KEY'
    required: true
  source:  # id of input
    description: 'file to be uploaded to s3'
    required: true
outputs:
  success: 
    description: 'successful'
runs:
  using: 'node12'
  main: './src/CoCreate-s3.js'
   

 